### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by paunsurfer** [Alwinator/ha-hello-fairy-integration#1]
First of all, great project!

I was about to start working on this myself, as the product is very interesting and I would love HA control over it.

I assume that this integration requires a bluetooth dongle for HA, but i'm wondering: Would it work with a bluetooth proxy?

i.e. https://esphome.io/projects/?type=bluetooth

I'm looking to get xmas lights controlled by HA, but the NUC is of course too far away.

Is there anything i can help test to assist you with this project?

**Comment by Alwinator** [comment]
@paunsurfer I am glad that you like my project. It is still work in progress and I continue from time to time after my paid work.

It would be great if you could support with testing and development. Are you experienced in Python?

Alwin

**Comment by paunsurfer** [comment]
I have a small amount of python experience, and a lot of experience with HA, Automation etc. I would defiantly be able to help intercept some codes etc with a little guidance

**Comment by gitothy** [comment]
Hi @Alwinator thanks for your efforts here. I've recently purchased a set of Hello Fairy lights and be happy to help with any testing or development.

Wondering if it's worth you feeding what you have here in to the seed HA 'LED BLE' component?

**Comment by Alwinator** [comment]
@gitothy @paunsurfer Unfortunately, I stopped working on this project because the channel of my Hello Fairy Lights conflicted with my new TV. So, I gave my Fairy Lights to a friend. I will achieve this repository now. However, feel free to copy code and continue developing on your own.
